In [1]:
import pandas as pd

In [2]:
!ls csvs/

2018-04-26_through_2018-05-26.csv  2018-08-27_through_2018-09-26.csv
2018-05-27_through_2018-06-26.csv  2018-09-27_through_2018-10-27.csv
2018-06-27_through_2018-07-27.csv  2018-10-28_through-2018-11-27.csv
2018-07-28_through_2018-08-26.csv  2018-11-28_through_2018-12-28.csv

In [3]:
file = open("./csvs/2018-08-27_through_2018-09-26.csv").readlines()

#### Delete the \n characters at the end of each line

In [4]:
for index,line in enumerate(file):
    file[index] = line.replace('\n','')

In [5]:
file[:5]

['Foods',
 'Date,Calories In',
 '"2018-08-27","0"',
 '"2018-08-28","0"',
 '"2018-08-29","0"']

In [6]:
file[30:40]

['"2018-09-24","0"',
 '"2018-09-25","0"',
 '"2018-09-26","0"',
 '',
 'Activities',
 'Date,Calories Burned,Steps,Distance,Floors,Minutes Sedentary,Minutes Lightly Active,Minutes Fairly Active,Minutes Very Active,Activity Calories',
 '"2018-08-27","4,458","15,714","7.48","15","608","259","9","96","2,692"',
 '"2018-08-28","3,757","12,569","5.93","14","717","218","8","58","1,874"',
 '"2018-08-29","3,222","8,559","4.04","16","853","166","4","35","1,266"',
 '"2018-08-30","3,253","6,682","3.15","7","793","234","14","9","1,389"']

### I noticed what seperates these two categories is a newline char, so I've gone ahead and made that the point at which we stop capturing for "food"

In [7]:
def grab_foods(file):
    foods = []
    for line in file:
        if line == "":
            break
        foods.append(line)
    foods = foods[1:]
    return foods


def remove_foods(file):
    file = file.copy()
    while True:
        if file.pop(0) == '':
            break
    
    file.pop(0) ## Removes the "Activites"
    file.pop(0) ## Removes "Column names"
    
    return file

In [8]:
foods = grab_foods(file)

In [9]:
foods[:7]

['Date,Calories In',
 '"2018-08-27","0"',
 '"2018-08-28","0"',
 '"2018-08-29","0"',
 '"2018-08-30","0"',
 '"2018-08-31","0"',
 '"2018-09-01","0"']

In [10]:
file2 = remove_foods(file)

## Grab location of index for everything in the Activities category

In [11]:
for index, string in enumerate(file2[1].split('"')):
    if string is not "" and string is not ",":
        print(f'the string  {string} is located at index: {index}')
        print('')

the string  2018-08-28 is located at index: 1

the string  3,757 is located at index: 3

the string  12,569 is located at index: 5

the string  5.93 is located at index: 7

the string  14 is located at index: 9

the string  717 is located at index: 11

the string  218 is located at index: 13

the string  8 is located at index: 15

the string  58 is located at index: 17

the string  1,874 is located at index: 19

In [12]:
split_str = file2[1].split('"')

In [13]:
abc = {'Calories': split_str[3], 'Steps': split_str[5]}

In [14]:
abc

{'Calories': '3,757', 'Steps': '12,569'}

In [15]:
def grab_activities(file):
    file = file.copy()
    file = remove_foods(file)
    activities = {}
    for string in file:
        ### This checks to see if we hit the next empty string signifying we've oved on to food logs
        if string == "":
            break
        x = string.split('"')
        activities[x[1]] = {'total_calories':x[3],
                            'steps':x[5],
                           'distance':x[7],
                           'floors':x[9],
                           'mins_sedentary':x[11],
                           'mins_active_light':x[13],
                           'mins_active_med':x[15],
                           'mins_active_high':x[17],
                           'activity_calories':x[19]
                           } 
        
    return activities

In [16]:
activities = grab_activities(file)

In [17]:
def remove_activities(file):
    file = file.copy()
    file = remove_foods(file)
    while True:
        if file.pop(0) == '':
            break
            
    return file

In [18]:
zzz = remove_activities(file)

In [19]:
zzz

['Food Log 20180827',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180828',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180829',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180830',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180831',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180901',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180902',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180903',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180904',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180905',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180906',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180907',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180908',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180909',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180910',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180911',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180912',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180913',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180914',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180915',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180916',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180917',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180918',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180919',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180920',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180921',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180922',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180923',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180924',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180925',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '',
 'Food Log 20180926',
 'Daily Totals',
 '"","Calories","0"',
 '"","Fat","0 g"',
 '"","Fiber","0 g"',
 '"","Carbs","0 g"',
 '"","Sodium","0 mg"',
 '"","Protein","0 g"',
 '"","Water","0 fl oz"',
 '']

In [20]:
def grab_food_logs(file):
    file = file.copy()
    file = remove_foods(file)
    file = remove_activities(file)
    food_logs = {}
    while True:
        food_log = file.pop(0).split()[2]
        file.pop(0)
        calories = file.pop(0).split(',')[2].replace('"','')
        fat = file.pop(0).split(',')[2].replace('"','')
        fiber = file.pop(0).split(',')[2].replace('"','')
        carbs = file.pop(0).split(',')[2].replace('"','')
        sodium = file.pop(0).split(',')[2].replace('"','')
        protien = file.pop(0).split(',')[2].replace('"','')
        water= file.pop(0).split(',')[2].replace('"','')
        file.pop(0)
    
        food_logs[food_log] ={'calories' : calories,
                         'fat' : fat,
                         'fiber' : fiber,
                         'carbs': carbs,
                         'sodium' : sodium,
                         'protien' :protien,
                         'water' : water}
        if len(file) == 0:
            return food_logs

In [21]:
food_logs = grab_food_logs(file)

In [22]:
pd.DataFrame(food_logs).T

         calories carbs  fat fiber protien sodium    water
20180828        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180829        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180830        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180831        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180901        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180902        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180903        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180904        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180905        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180906        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180907        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180908        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180909        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180910        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180911        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180912        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180913        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180914        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180915        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180916        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180917        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180918        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180919        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180920        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180921        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180922        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180923        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180924        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180925        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
20180926        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz

In [23]:
pd.DataFrame(activities).T

,activity_calories,distance,floors,mins_active_high,mins_active_light,mins_active_med,mins_sedentary,steps,total_calories
2018-08-27,"2,692",7.48,15,96,259,9,608,"15,714","4,458"
2018-08-28,"1,874",5.93,14,58,218,8,717,"12,569","3,757"
2018-08-29,"1,266",4.04,16,35,166,4,853,"8,559","3,222"
2018-08-30,"1,389",3.15,7,9,234,14,793,"6,682","3,253"
2018-08-31,"2,640",7.46,17,104,211,8,744,"15,415","4,415"
2018-09-01,852,1.86,7,5,133,13,798,"3,952","3,020"
2018-09-02,811,1.5,6,0,163,0,872,"3,181","2,918"
2018-09-03,915,2.24,6,15,155,8,754,"4,743","2,936"
2018-09-04,"1,374",3.46,5,3,269,6,631,"7,343","3,201"
2018-09-05,"1,514",3.86,18,33,184,16,"1,040","7,943","3,395"
2018-09-06,983,2.66,5,0,195,0,746,"5,641","2,907"
2018-09-07,"1,922",4.52,7,43,242,20,683,"9,591","3,829"
2018-09-08,"2,230",6.65,16,76,237,16,634,"13,798","4,031"
2018-09-09,"1,872",4.41,9,46,234,22,734,"9,360","3,682"
2018-09-10,"1,002",2.81,18,4,158,10,835,"5,951","2,977"
2018-09-11,829,2.1,1,4,154,6,781,"4,446","2,824"
2018-09-12,"1,175",3.54,6,13,179,17,676,"7,512","3,047"
2018-09-13,"1,118",3.06,10,13,190,1,885,"6,480","3,044"
2018-09-14,"1,125",3.31,3,7,179,18,871,"7,021","3,080"
2018-09-15,"1,287",4.45,77,51,134,23,849,"9,445","3,180"
2018-09-16,"1,494",4.25,102,38,184,30,586,"9,015","3,344"
2018-09-17,985,2.65,2,13,134,24,990,"5,628","2,952"
2018-09-18,"1,074",2.95,11,11,196,1,866,"6,247","2,997"
2018-09-19,"1,195",3.32,14,8,218,2,768,"7,034","3,044"
2018-09-20,"1,565",4.68,8,56,156,10,844,"9,920","3,517"
2018-09-21,"1,172",3.86,9,26,163,6,797,"8,185","3,105"
2018-09-22,"3,596",7.65,10,98,319,78,581,"16,219","5,199"
2018-09-23,745,2.74,12,46,46,7,773,"5,807","2,787"
2018-09-24,822,2.12,7,0,167,0,841,"4,500","2,771"
2018-09-25,853,2.46,6,11,142,2,767,"5,219","2,820"
2018-09-26,"1,677",4.94,9,63,163,3,707,"10,466","3,613"

In [24]:
pd.DataFrame(foods)

                   0
0   Date,Calories In
1   "2018-08-27","0"
2   "2018-08-28","0"
3   "2018-08-29","0"
4   "2018-08-30","0"
5   "2018-08-31","0"
6   "2018-09-01","0"
7   "2018-09-02","0"
8   "2018-09-03","0"
9   "2018-09-04","0"
10  "2018-09-05","0"
11  "2018-09-06","0"
12  "2018-09-07","0"
13  "2018-09-08","0"
14  "2018-09-09","0"
15  "2018-09-10","0"
16  "2018-09-11","0"
17  "2018-09-12","0"
18  "2018-09-13","0"
19  "2018-09-14","0"
20  "2018-09-15","0"
21  "2018-09-16","0"
22  "2018-09-17","0"
23  "2018-09-18","0"
24  "2018-09-19","0"
25  "2018-09-20","0"
26  "2018-09-21","0"
27  "2018-09-22","0"
28  "2018-09-23","0"
29  "2018-09-24","0"
30  "2018-09-25","0"
31  "2018-09-26","0"

In [25]:
food_dict = {}
foodz = foods.copy()[1:]
for i in foodz:
    split_str = i.split('"')
    print(split_str)
    food_dict[split_str[1]] = {'calories':split_str[3]}

['', '2018-08-27', ',', '0', '']
['', '2018-08-28', ',', '0', '']
['', '2018-08-29', ',', '0', '']
['', '2018-08-30', ',', '0', '']
['', '2018-08-31', ',', '0', '']
['', '2018-09-01', ',', '0', '']
['', '2018-09-02', ',', '0', '']
['', '2018-09-03', ',', '0', '']
['', '2018-09-04', ',', '0', '']
['', '2018-09-05', ',', '0', '']
['', '2018-09-06', ',', '0', '']
['', '2018-09-07', ',', '0', '']
['', '2018-09-08', ',', '0', '']
['', '2018-09-09', ',', '0', '']
['', '2018-09-10', ',', '0', '']
['', '2018-09-11', ',', '0', '']
['', '2018-09-12', ',', '0', '']
['', '2018-09-13', ',', '0', '']
['', '2018-09-14', ',', '0', '']
['', '2018-09-15', ',', '0', '']
['', '2018-09-16', ',', '0', '']
['', '2018-09-17', ',', '0', '']
['', '2018-09-18', ',', '0', '']
['', '2018-09-19', ',', '0', '']
['', '2018-09-20', ',', '0', '']
['', '2018-09-21', ',', '0', '']
['', '2018-09-22', ',', '0', '']
['', '2018-09-23', ',', '0', '']
['', '2018-09-24', ',', '0', '']
['', '2018-09-25', ',', '0', '']
['', '2018-09-26', ',', '0', '']

In [26]:
pd.DataFrame(food_dict).T

           calories
2018-08-27        0
2018-08-28        0
2018-08-29        0
2018-08-30        0
2018-08-31        0
2018-09-01        0
2018-09-02        0
2018-09-03        0
2018-09-04        0
2018-09-05        0
2018-09-06        0
2018-09-07        0
2018-09-08        0
2018-09-09        0
2018-09-10        0
2018-09-11        0
2018-09-12        0
2018-09-13        0
2018-09-14        0
2018-09-15        0
2018-09-16        0
2018-09-17        0
2018-09-18        0
2018-09-19        0
2018-09-20        0
2018-09-21        0
2018-09-22        0
2018-09-23        0
2018-09-24        0
2018-09-25        0
2018-09-26        0

In [27]:
foods

['Date,Calories In',
 '"2018-08-27","0"',
 '"2018-08-28","0"',
 '"2018-08-29","0"',
 '"2018-08-30","0"',
 '"2018-08-31","0"',
 '"2018-09-01","0"',
 '"2018-09-02","0"',
 '"2018-09-03","0"',
 '"2018-09-04","0"',
 '"2018-09-05","0"',
 '"2018-09-06","0"',
 '"2018-09-07","0"',
 '"2018-09-08","0"',
 '"2018-09-09","0"',
 '"2018-09-10","0"',
 '"2018-09-11","0"',
 '"2018-09-12","0"',
 '"2018-09-13","0"',
 '"2018-09-14","0"',
 '"2018-09-15","0"',
 '"2018-09-16","0"',
 '"2018-09-17","0"',
 '"2018-09-18","0"',
 '"2018-09-19","0"',
 '"2018-09-20","0"',
 '"2018-09-21","0"',
 '"2018-09-22","0"',
 '"2018-09-23","0"',
 '"2018-09-24","0"',
 '"2018-09-25","0"',
 '"2018-09-26","0"']

In [28]:
import acquire as ak

In [29]:
! ls csvs

2018-04-26_through_2018-05-26.csv  2018-08-27_through_2018-09-26.csv
2018-05-27_through_2018-06-26.csv  2018-09-27_through_2018-10-27.csv
2018-06-27_through_2018-07-27.csv  2018-10-28_through-2018-11-27.csv
2018-07-28_through_2018-08-26.csv  2018-11-28_through_2018-12-28.csv

In [30]:
csvs = ['2018-04-26_through_2018-05-26.csv',  '2018-08-27_through_2018-09-26.csv',
'2018-05-27_through_2018-06-26.csv',  '2018-09-27_through_2018-10-27.csv',
'2018-06-27_through_2018-07-27.csv',  '2018-10-28_through-2018-11-27.csv',
'2018-07-28_through_2018-08-26.csv',  '2018-11-28_through_2018-12-28.csv']

In [31]:
df_lists = []
for i in csvs:
    df_lists.append(ak.csv_to_dataframes('csvs/'+i))

In [32]:
foods = []
activ = []
logs = []
for i in df_lists:
    foods.append(i[0])
    activ.append(i[1])
    logs.append(i[2])

In [33]:
f_df = pd.concat(foods)
a_df = pd.concat(activ)
l_df = pd.concat(logs)

In [34]:
cols = list(l_df.columns)

In [35]:
l_df[cols[6]].value_counts()

0 fl oz    239
Name: water, dtype: int64

In [36]:
ak.acquire_fitbit()

[           calories
 2018-04-26        0
 2018-04-27        0
 2018-04-28        0
 2018-04-29        0
 2018-04-30        0
 2018-05-01        0
 2018-05-02        0
 2018-05-03        0
 2018-05-04        0
 2018-05-05        0
 2018-05-06        0
 2018-05-07        0
 2018-05-08        0
 2018-05-09        0
 2018-05-10        0
 2018-05-11        0
 2018-05-12        0
 2018-05-13        0
 2018-05-14        0
 2018-05-15        0
 2018-05-16        0
 2018-05-17        0
 2018-05-18        0
 2018-05-19        0
 2018-05-20        0
 2018-05-21        0
 2018-05-22        0
 2018-05-23        0
 2018-05-24        0
 2018-05-25        0
 ...             ...
 2018-11-29        0
 2018-11-30        0
 2018-12-01        0
 2018-12-02        0
 2018-12-03        0
 2018-12-04        0
 2018-12-05        0
 2018-12-06        0
 2018-12-07        0
 2018-12-08        0
 2018-12-09        0
 2018-12-10        0
 2018-12-11        0
 2018-12-12        0
 2018-12-13        0
 2018-12-14        0
 2018-12-15        0
 2018-12-16        0
 2018-12-17        0
 2018-12-18        0
 2018-12-19        0
 2018-12-20        0
 2018-12-21        0
 2018-12-22        0
 2018-12-23        0
 2018-12-24        0
 2018-12-25        0
 2018-12-26        0
 2018-12-27        0
 2018-12-28        0

 [247 rows x 1 columns],
            activity_calories distance floors mins_active_high  \
 2018-04-26               566     1.38      2                0
 2018-04-27             1,752      4.7     19               17
 2018-04-28             1,124     1.66      2               11
 2018-04-29               602     0.77      0                0
 2018-04-30               540     0.62      0                0
 2018-05-01             1,068     1.22      0                2
 2018-05-02               419     0.65      0                0
 2018-05-03             1,006     1.05      0                0
 2018-05-04               269     0.43      1                0
 2018-05-05               326     0.39      0                0
 2018-05-06               506     0.65      0                0
 2018-05-07               283     0.45      0                0
 2018-05-08               410     0.56      2                2
 2018-05-09                 8     0.01      0                0
 2018-05-10               924     0.64      0                4
 2018-05-11               727     1.31      1                0
 2018-05-12             1,113     1.95      2                7
 2018-05-13               394      0.8      0                0
 2018-05-14               794     1.75      0                0
 2018-05-15             1,011     2.03      0                0
 2018-05-16             1,396     2.77      1                6
 2018-05-17               897     1.92      4                0
 2018-05-18             2,549     6.58      7               92
 2018-05-19             2,228     7.04      7               89
 2018-05-20               978     2.35      3                6
 2018-05-21               932     1.88      3                0
 2018-05-22             1,460     2.21      1                2
 2018-05-23             1,765     3.25      0               14
 2018-05-24               723     1.64      0                0
 2018-05-25             1,127     2.54      1               13
 ...                      ...      ...    ...              ...
 2018-08-06             1,121     2.92      7                0
 2018-08-07             1,185     3.09      6                0
 2018-08-08             1,375     3.67     12                9
 2018-08-09             2,566     7.37     13               77
 2018-08-10             1,730     3.52      2               14
 2018-08-11             2,616     8.26     21               94
 2018-08-12             2,224     5.28      6               57
 2018-08-13             2,424     8.02     17               98
 2018-08-14             1,598     3.98     11               12
 2018-08-15             2,158     5.78      8               56
 2018-08-16             1,678     3.79     18                6
 2018-08-17             2,686     7.77     11              125
 2018-08-18               972      2.2      8                0
 2018-08-19             2,595     6.35     16               83
 2018-08-20             2,190     5.55      3               64
 2018-08-21             1,319     2.96      4                8
 2018-08-22             1,852     4.09      5               48
 2018-08-23             2,261     6.93     11               79
 2018-08-24                32     0.03      0                0
 2018-08-25             1,731     1.91      7               23
 2018-08-26                51      0.1      1                0
 2018-11-28             1,361     3.59     16                0
 2018-11-29             2,051     6.56     18               53
 2018-11-30             1,577     4.51     14                6
 2018-12-01             2,124     7.27      7               67
 2018-12-02             2,305     6.23    195               70
 2018-12-03             1,993     6.12      6               51
 2018-12-04             1,663     6.49     13               67
 2018-12-05             1,968     6.52     12               69
 2018-12-06             1,962     6.96      9               78

            mins_active_light mins_active_med mins_sedentary   steps  \
 2018-04-26                93               0          1,347   2,931
 2018-04-27               219              46          1,158   9,971
 2018-04-28               155              22            702   3,521
 2018-04-29               122               0            891   1,639
 2018-04-30               104               0            880   1,323
 2018-05-01               167              13            919   2,581
 2018-05-02                90               0            927   1,372
 2018-05-03               157              16            876   2,232
 2018-05-04                61               0          1,012     904
 2018-05-05                68               0            969     833
 2018-05-06               103               0            976   1,383
 2018-05-07                63               0            907     952
 2018-05-08                53              17          1,221   1,187
 2018-05-09                 2               0          1,438      21
 2018-05-10               136               5          1,295   1,364
 2018-05-11               130               0            947   2,771
 2018-05-12               184               4            756   4,125
 2018-05-13                84               0            895   1,689
 2018-05-14               119              19            959   3,710
 2018-05-15               183               9            767   4,313
 2018-05-16               234               5            825   5,882
 2018-05-17               158               0            867   4,080
 2018-05-18               178              67            682  13,958
 2018-05-19               193              34            646  14,917
 2018-05-20               174               5            795   4,986
 2018-05-21               182               0            727   3,989
 2018-05-22               209              33            625   4,680
 2018-05-23               241              42            921   6,889
 2018-05-24               143               0            804   3,470
 2018-05-25               145              32            821   5,389
 ...                      ...             ...            ...     ...
 2018-08-06               210               0            775   6,185
 2018-08-07               223               0            777   6,558
 2018-08-08               220              13            724   7,772
 2018-08-09               285              17          1,061  15,635
 2018-08-10               293               9            641   7,470
 2018-08-11               260              20            448  17,519
 2018-08-12               257              21            585  11,193
 2018-08-13               222              25            771  17,014
 2018-08-14               264               9            719   8,448
 2018-08-15               213              23            704  12,259
 2018-08-16               311               7            877   8,039
 2018-08-17               198               9            608  16,482
 2018-08-18               198               0            551   4,657
 2018-08-19               243              30            796  13,461
 2018-08-20               239               1            624  11,763
 2018-08-21               212               6            689   6,274
 2018-08-22               200              13            845   8,678
 2018-08-23               210              18            653  14,696
 2018-08-24                 7               0            994      68
 2018-08-25               204              23          1,190   4,054
 2018-08-26                13               0             28     207
 2018-11-28               272               0            717   7,602
 2018-11-29               258              15            717  12,380
 2018-11-30               288              12            699   9,559
 2018-12-01               233              22            527  14,510
 2018-12-02               265              13            725  13,257
 2018-12-03               219              40            782  12,915
 2018-12-04               199              11            608  13,763
 2018-12-05               200              12            739  13,865
 2018-12-06               198               4            647  14,774

            total_calories
 2018-04-26          2,635
 2018-04-27          3,649
 2018-04-28          3,379
 2018-04-29          2,851
 2018-04-30          2,825
 2018-05-01          3,292
 2018-05-02          2,660
 2018-05-03          3,121
 2018-05-04          2,522
 2018-05-05          2,551
 2018-05-06          2,771
 2018-05-07          2,524
 2018-05-08          2,591
 2018-05-09          2,153
 2018-05-10          3,081
 2018-05-11          2,950
 2018-05-12          3,318
 2018-05-13          2,572
 2018-05-14          2,966
 2018-05-15          3,152
 2018-05-16          3,497
 2018-05-17          3,066
 2018-05-18          4,376
 2018-05-19          4,112
 2018-05-20          3,098
 2018-05-21          3,009
 2018-05-22          3,581
 2018-05-23          3,772
 2018-05-24          2,756
 2018-05-25          3,155
 ...                   ...
 2018-08-06          3,150
 2018-08-07          3,152
 2018-08-08          3,341
 2018-08-09          4,339
 2018-08-10          3,667
 2018-08-11          4,392
 2018-08-12          4,011
 2018-08-13          4,196
 2018-08-14          3,454
 2018-08-15          4,079
 2018-08-16          3,490
 2018-08-17          4,610
 2018-08-18          2,921
 2018-08-19          4,381
 2018-08-20          4,041
 2018-08-21          3,393
 2018-08-22          3,811
 2018-08-23          4,232
 2018-08-24          2,168
 2018-08-25          3,719
 2018-08-26            799
 2018-11-28          3,088
 2018-11-29          3,693
 2018-11-30          3,269
 2018-12-01          3,813
 2018-12-02          3,957
 2018-12-03          3,660
 2018-12-04          3,384
 2018-12-05          3,670
 2018-12-06          3,669

 [225 rows x 9 columns],
          calories carbs  fat fiber protien sodium    water
 20180427        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180428        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180429        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180430        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180501        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180502        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180503        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180504        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180505        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180506        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180507        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180508        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180509        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180510        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180511        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180512        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180513        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180514        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180515        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180516        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180517        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180518        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180519        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180520        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180521        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180522        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180523        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180524        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180525        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20180526        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 ...           ...   ...  ...   ...     ...    ...      ...
 20181129        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181130        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181201        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181202        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181203        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181204        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181205        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181206        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181207        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181208        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181209        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181210        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181211        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181212        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181213        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181214        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181215        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181216        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181217        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181218        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181219        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181220        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181221        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181222        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181223        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181224        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181225        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181226        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181227        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz
 20181228        0   0 g  0 g   0 g     0 g   0 mg  0 fl oz

 [239 rows x 7 columns]]